[2025-03-02T07:43:14.956+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T07:43:14.962+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_daily_load.fetch_and_load_data manual__2025-03-02T07:41:12.066646+00:00 [queued]>
[2025-03-02T07:43:14.965+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_daily_load.fetch_and_load_data manual__2025-03-02T07:41:12.066646+00:00 [queued]>
[2025-03-02T07:43:14.965+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-03-02T07:43:14.969+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): fetch_and_load_data> on 2025-03-02 07:41:12.066646+00:00
[2025-03-02T07:43:14.973+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_price_daily_load', 'fetch_and_load_data', 'manual__2025-03-02T07:41:12.066646+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/daily_stock_price.py', '--cfg-path', '/tmp/tmpz04gw6y2']
[2025-03-02T07:43:14.975+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask fetch_and_load_data
[2025-03-02T07:43:14.975+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=317) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-02T07:43:14.976+0000] {standard_task_runner.py:72} INFO - Started process 320 to run task
[2025-03-02T07:43:15.010+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_price_daily_load.fetch_and_load_data manual__2025-03-02T07:41:12.066646+00:00 [running]> on host 77db11e846ba
[2025-03-02T07:43:15.039+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_daily_load' AIRFLOW_CTX_TASK_ID='fetch_and_load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T07:41:12.066646+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T07:41:12.066646+00:00'
[2025-03-02T07:43:15.039+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-02T07:43:15.045+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-03-02T07:43:15.046+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-02T07:43:15.046+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-02T07:43:15.818+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-02T07:43:15.820+0000] {logging_mixin.py:190} INFO - YF.download() has changed argument auto_adjust default to True
[2025-03-02T07:43:16.119+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/daily_stock_price.py:82 FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
[2025-03-02T07:43:16.121+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/daily_stock_price.py:83 FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
[2025-03-02T07:43:16.122+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/daily_stock_price.py:84 FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
[2025-03-02T07:43:16.122+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/daily_stock_price.py:85 FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
[2025-03-02T07:43:16.123+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/daily_stock_price.py", line 86, in fetch_and_load_data
    int(row["volume"]) if not pd.isna(row["volume"]) else 0
                              ^^
NameError: name 'pd' is not defined
[2025-03-02T07:43:16.132+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=stock_price_daily_load, task_id=fetch_and_load_data, run_id=manual__2025-03-02T07:41:12.066646+00:00, execution_date=20250302T074112, start_date=20250302T074314, end_date=20250302T074316
[2025-03-02T07:43:16.139+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-02T07:43:16.139+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 20 for task fetch_and_load_data (name 'pd' is not defined; 320)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/daily_stock_price.py", line 86, in fetch_and_load_data
    int(row["volume"]) if not pd.isna(row["volume"]) else 0
                              ^^
NameError: name 'pd' is not defined
[2025-03-02T07:43:16.175+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-02T07:43:16.190+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-02T07:43:16.191+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
