[2025-03-05T05:53:16.878+0000] {processor.py:186} INFO - Started process (PID=235) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:53:16.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:53:16.880+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:53:16.880+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:53:16.893+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:53:16.891+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:53:16.894+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:53:16.906+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.031 seconds
[2025-03-05T05:53:47.650+0000] {processor.py:186} INFO - Started process (PID=288) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:53:47.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:53:47.652+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:53:47.651+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:53:47.659+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:53:47.658+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:53:47.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:53:47.672+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.025 seconds
[2025-03-05T05:54:18.343+0000] {processor.py:186} INFO - Started process (PID=299) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:54:18.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:54:18.345+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:54:18.344+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:54:18.356+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:54:18.352+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:54:18.357+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:54:18.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.029 seconds
[2025-03-05T05:54:49.055+0000] {processor.py:186} INFO - Started process (PID=310) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:54:49.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:54:49.057+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:54:49.056+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:54:49.067+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:54:49.065+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:54:49.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:54:49.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.029 seconds
[2025-03-05T05:55:19.703+0000] {processor.py:186} INFO - Started process (PID=321) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:55:19.704+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:55:19.705+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:55:19.705+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:55:19.718+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:55:19.715+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:55:19.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:55:19.732+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.032 seconds
[2025-03-05T05:55:50.390+0000] {processor.py:186} INFO - Started process (PID=332) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:55:50.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:55:50.392+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:55:50.391+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:55:50.400+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:55:50.398+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:55:50.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:55:50.414+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.027 seconds
[2025-03-05T05:56:21.049+0000] {processor.py:186} INFO - Started process (PID=343) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:56:21.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:56:21.051+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:56:21.051+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:56:21.060+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:56:21.058+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:56:21.061+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:56:21.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.028 seconds
[2025-03-05T05:56:51.719+0000] {processor.py:186} INFO - Started process (PID=354) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:56:51.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:56:51.721+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:56:51.721+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:56:51.731+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:56:51.729+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:56:51.732+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:56:51.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.027 seconds
[2025-03-05T05:57:22.317+0000] {processor.py:186} INFO - Started process (PID=365) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:57:22.317+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:57:22.318+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:57:22.318+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:57:22.327+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:57:22.325+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:57:22.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:57:22.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.026 seconds
[2025-03-05T05:57:52.977+0000] {processor.py:186} INFO - Started process (PID=376) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:57:52.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:57:52.979+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:57:52.979+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:57:52.991+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:57:52.988+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:57:52.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:57:53.005+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.032 seconds
[2025-03-05T05:58:23.721+0000] {processor.py:186} INFO - Started process (PID=387) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:58:23.721+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:58:23.723+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:58:23.722+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:58:23.731+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:58:23.729+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:58:23.732+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:58:23.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.030 seconds
[2025-03-05T05:58:54.367+0000] {processor.py:186} INFO - Started process (PID=398) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:58:54.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:58:54.369+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:58:54.369+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:58:54.378+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:58:54.376+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:58:54.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:58:54.392+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.028 seconds
[2025-03-05T05:59:24.978+0000] {processor.py:186} INFO - Started process (PID=409) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:59:24.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:59:24.980+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:59:24.980+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:59:24.990+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:59:24.988+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:59:24.991+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:59:25.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.033 seconds
[2025-03-05T05:59:55.650+0000] {processor.py:186} INFO - Started process (PID=420) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:59:55.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T05:59:55.652+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:59:55.652+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:59:55.660+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:59:55.658+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T05:59:55.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T05:59:55.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.026 seconds
[2025-03-05T06:00:26.272+0000] {processor.py:186} INFO - Started process (PID=431) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:00:26.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:00:26.274+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:00:26.273+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:00:26.283+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:00:26.281+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:00:26.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:00:26.296+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.028 seconds
[2025-03-05T06:00:56.959+0000] {processor.py:186} INFO - Started process (PID=442) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:00:56.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:00:56.961+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:00:56.961+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:00:56.970+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:00:56.968+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:00:56.971+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:00:56.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.027 seconds
[2025-03-05T06:01:27.587+0000] {processor.py:186} INFO - Started process (PID=453) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:01:27.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:01:27.589+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:01:27.589+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:01:27.600+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:01:27.598+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:01:27.601+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:01:27.615+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.031 seconds
[2025-03-05T06:01:58.287+0000] {processor.py:186} INFO - Started process (PID=470) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:01:58.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:01:58.289+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:01:58.288+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:01:58.297+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:01:58.295+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:01:58.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:01:58.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.025 seconds
[2025-03-05T06:02:28.952+0000] {processor.py:186} INFO - Started process (PID=481) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:02:28.953+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:02:28.954+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:02:28.954+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:02:28.962+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:02:28.961+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:02:28.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:02:28.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.026 seconds
[2025-03-05T06:02:59.619+0000] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:02:59.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:02:59.621+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:02:59.621+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:02:59.633+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:02:59.630+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:02:59.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:02:59.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.032 seconds
[2025-03-05T06:03:30.331+0000] {processor.py:186} INFO - Started process (PID=503) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:03:30.332+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:03:30.333+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:03:30.333+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:03:30.342+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:03:30.340+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:03:30.343+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:03:30.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.028 seconds
[2025-03-05T06:04:00.996+0000] {processor.py:186} INFO - Started process (PID=514) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:04:00.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:04:00.998+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:04:00.998+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:04:01.014+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:04:01.010+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:04:01.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:04:01.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.037 seconds
[2025-03-05T06:04:31.651+0000] {processor.py:186} INFO - Started process (PID=525) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:04:31.651+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:04:31.653+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:04:31.652+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:04:31.663+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:04:31.661+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:04:31.664+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:04:31.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.029 seconds
[2025-03-05T06:05:02.354+0000] {processor.py:186} INFO - Started process (PID=536) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:05:02.355+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:05:02.356+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:05:02.356+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:05:02.368+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:05:02.365+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:05:02.369+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:05:02.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.030 seconds
[2025-03-05T06:05:32.908+0000] {processor.py:186} INFO - Started process (PID=547) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:05:32.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:05:32.909+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:05:32.909+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:05:32.918+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:05:32.916+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:05:32.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:05:32.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.026 seconds
[2025-03-05T06:06:03.593+0000] {processor.py:186} INFO - Started process (PID=558) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:06:03.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:06:03.595+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:06:03.595+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:06:03.603+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:06:03.602+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:06:03.604+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:06:03.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.028 seconds
[2025-03-05T06:06:34.273+0000] {processor.py:186} INFO - Started process (PID=569) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:06:34.273+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:06:34.274+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:06:34.274+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:06:34.284+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:06:34.282+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:06:34.285+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:06:34.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.027 seconds
[2025-03-05T06:07:04.997+0000] {processor.py:186} INFO - Started process (PID=580) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:07:04.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:07:04.999+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:07:04.999+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:07:05.012+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:07:05.009+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:07:05.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:07:05.026+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.032 seconds
[2025-03-05T06:07:35.696+0000] {processor.py:186} INFO - Started process (PID=591) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:07:35.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:07:35.698+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:07:35.698+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:07:35.707+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:07:35.704+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:07:35.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:07:35.720+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.027 seconds
[2025-03-05T06:08:06.372+0000] {processor.py:186} INFO - Started process (PID=602) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:08:06.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:08:06.374+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:08:06.374+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:08:06.386+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:08:06.383+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:08:06.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:08:06.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.031 seconds
[2025-03-05T06:08:37.051+0000] {processor.py:186} INFO - Started process (PID=613) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:08:37.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:08:37.053+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:08:37.053+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:08:37.062+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:08:37.060+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:08:37.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:08:37.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.027 seconds
[2025-03-05T06:09:07.721+0000] {processor.py:186} INFO - Started process (PID=624) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:09:07.721+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:09:07.723+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:09:07.723+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:09:07.732+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:09:07.730+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:09:07.733+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:09:07.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.027 seconds
[2025-03-05T06:09:38.352+0000] {processor.py:186} INFO - Started process (PID=635) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:09:38.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:09:38.354+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:09:38.354+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:09:38.364+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:09:38.362+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:09:38.365+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:09:38.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.029 seconds
[2025-03-05T06:10:09.053+0000] {processor.py:186} INFO - Started process (PID=646) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:10:09.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:10:09.055+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:10:09.054+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:10:09.063+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:10:09.061+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:10:09.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:10:09.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.027 seconds
[2025-03-05T06:10:39.706+0000] {processor.py:186} INFO - Started process (PID=657) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:10:39.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:10:39.709+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:10:39.709+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:10:39.718+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:10:39.716+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:10:39.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:10:39.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.028 seconds
[2025-03-05T06:11:10.366+0000] {processor.py:186} INFO - Started process (PID=668) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:11:10.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:11:10.368+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:11:10.368+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:11:10.379+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:11:10.377+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:11:10.380+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:11:10.392+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.029 seconds
[2025-03-05T06:11:41.030+0000] {processor.py:186} INFO - Started process (PID=679) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:11:41.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:11:41.032+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:11:41.032+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:11:41.044+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:11:41.042+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:11:41.045+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:11:41.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.030 seconds
[2025-03-05T06:12:11.662+0000] {processor.py:186} INFO - Started process (PID=690) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:12:11.662+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:12:11.664+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:12:11.664+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:12:11.672+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:12:11.671+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:12:11.673+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:12:11.685+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.026 seconds
[2025-03-05T06:12:42.358+0000] {processor.py:186} INFO - Started process (PID=701) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:12:42.359+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:12:42.360+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:12:42.360+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:12:42.371+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:12:42.369+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:12:42.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:12:42.384+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.030 seconds
[2025-03-05T06:13:13.039+0000] {processor.py:186} INFO - Started process (PID=712) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:13:13.039+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:13:13.041+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:13:13.041+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:13:13.050+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:13:13.048+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:13:13.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:13:13.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.026 seconds
[2025-03-05T06:13:43.771+0000] {processor.py:186} INFO - Started process (PID=723) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:13:43.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:13:43.773+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:13:43.773+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:13:43.784+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:13:43.782+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:13:43.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:13:43.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.041 seconds
[2025-03-05T06:14:14.418+0000] {processor.py:186} INFO - Started process (PID=734) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:14:14.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:14:14.420+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:14:14.420+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:14:14.431+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:14:14.429+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:14:14.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:14:14.446+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.031 seconds
[2025-03-05T06:14:45.097+0000] {processor.py:186} INFO - Started process (PID=745) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:14:45.098+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:14:45.099+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:14:45.099+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:14:45.112+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:14:45.109+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:14:45.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:14:45.125+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.031 seconds
[2025-03-05T06:15:15.795+0000] {processor.py:186} INFO - Started process (PID=756) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:15:15.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:15:15.797+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:15:15.797+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:15:15.809+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:15:15.805+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:15:15.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:15:15.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.031 seconds
[2025-03-05T06:15:46.592+0000] {processor.py:186} INFO - Started process (PID=768) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:15:46.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:15:46.594+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:15:46.594+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:15:46.605+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:15:46.603+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:15:46.606+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:15:46.618+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.029 seconds
[2025-03-05T06:16:17.324+0000] {processor.py:186} INFO - Started process (PID=779) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:16:17.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:16:17.326+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:16:17.326+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:16:17.334+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:16:17.332+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:16:17.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:16:17.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.028 seconds
[2025-03-05T06:16:48.041+0000] {processor.py:186} INFO - Started process (PID=790) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:16:48.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:16:48.044+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:16:48.043+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:16:48.055+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:16:48.053+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:16:48.056+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:16:48.069+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.031 seconds
[2025-03-05T06:17:18.726+0000] {processor.py:186} INFO - Started process (PID=801) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:17:18.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:17:18.728+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:17:18.728+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:17:18.738+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:17:18.736+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:17:18.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:17:18.751+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.028 seconds
[2025-03-05T06:17:49.427+0000] {processor.py:186} INFO - Started process (PID=812) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:17:49.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:17:49.429+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:17:49.429+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:17:49.440+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:17:49.437+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5 (1).py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5 (1).py", line 10, in <module>
    from google.colab import userdata
ModuleNotFoundError: No module named 'google.colab'
[2025-03-05T06:17:49.441+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:17:49.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.029 seconds
[2025-03-05T06:46:13.546+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:46:13.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:46:13.548+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:13.548+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:46:13.581+0000] {processor.py:925} INFO - DAG(s) 'Stocks' retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:46:13.647+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:13.647+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:Stocks
[2025-03-05T06:46:13.654+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:13.654+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:Stocks
[2025-03-05T06:46:13.658+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:13.658+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:Stocks
[2025-03-05T06:46:13.664+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:13.664+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:Stocks
[2025-03-05T06:46:13.669+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:13.669+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:Stocks
[2025-03-05T06:46:13.675+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:13.674+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:Stocks
[2025-03-05T06:46:13.681+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:13.680+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:Stocks
[2025-03-05T06:46:13.681+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:13.681+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-03-05T06:46:13.689+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:13.689+0000] {dag.py:3252} INFO - Creating ORM DAG for Stocks
[2025-03-05T06:46:13.698+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:13.698+0000] {dag.py:4156} INFO - Setting next_dagrun for Stocks to 2025-03-04 02:30:00+00:00, run_after=2025-03-05 02:30:00+00:00
[2025-03-05T06:46:13.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.224 seconds
[2025-03-05T06:46:44.316+0000] {processor.py:186} INFO - Started process (PID=309) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:46:44.317+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:46:44.318+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:44.318+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:46:44.339+0000] {processor.py:925} INFO - DAG(s) 'Stocks' retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:46:44.351+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:44.351+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-03-05T06:46:44.366+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:46:44.366+0000] {dag.py:4156} INFO - Setting next_dagrun for Stocks to 2025-03-05 02:30:00+00:00, run_after=2025-03-06 02:30:00+00:00
[2025-03-05T06:46:44.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.069 seconds
[2025-03-05T06:47:15.029+0000] {processor.py:186} INFO - Started process (PID=320) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:47:15.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:47:15.031+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:47:15.031+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:47:15.050+0000] {processor.py:925} INFO - DAG(s) 'Stocks' retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:47:15.064+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:47:15.063+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-03-05T06:47:15.078+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:47:15.078+0000] {dag.py:4156} INFO - Setting next_dagrun for Stocks to 2025-03-05 02:30:00+00:00, run_after=2025-03-06 02:30:00+00:00
[2025-03-05T06:47:15.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.066 seconds
[2025-03-05T06:47:45.849+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:47:45.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:47:45.852+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:47:45.851+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:47:45.872+0000] {processor.py:925} INFO - DAG(s) 'Stocks' retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:47:45.883+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:47:45.883+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-03-05T06:47:45.899+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:47:45.899+0000] {dag.py:4156} INFO - Setting next_dagrun for Stocks to 2025-03-05 02:30:00+00:00, run_after=2025-03-06 02:30:00+00:00
[2025-03-05T06:47:45.916+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.070 seconds
[2025-03-05T06:48:16.602+0000] {processor.py:186} INFO - Started process (PID=342) to work on /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:48:16.603+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5 (1).py for tasks to queue
[2025-03-05T06:48:16.604+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:48:16.604+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:48:16.622+0000] {processor.py:925} INFO - DAG(s) 'Stocks' retrieved from /opt/airflow/dags/data226_hwk5 (1).py
[2025-03-05T06:48:16.632+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:48:16.632+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-03-05T06:48:16.646+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:48:16.646+0000] {dag.py:4156} INFO - Setting next_dagrun for Stocks to 2025-03-05 02:30:00+00:00, run_after=2025-03-06 02:30:00+00:00
[2025-03-05T06:48:16.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5 (1).py took 0.061 seconds
