[2025-03-05T05:50:41.084+0000] {processor.py:186} INFO - Started process (PID=233) to work on /opt/airflow/dags/data226_hwk5.py
[2025-03-05T05:50:41.084+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5.py for tasks to queue
[2025-03-05T05:50:41.085+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:50:41.085+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T05:50:41.092+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:50:41.091+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5.py", line 10
    !pip install snowflake-connector-python
    ^
SyntaxError: invalid syntax
[2025-03-05T05:50:41.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T05:50:41.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5.py took 0.023 seconds
[2025-03-05T05:51:11.662+0000] {processor.py:186} INFO - Started process (PID=287) to work on /opt/airflow/dags/data226_hwk5.py
[2025-03-05T05:51:11.663+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5.py for tasks to queue
[2025-03-05T05:51:11.664+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:51:11.664+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T05:51:11.670+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:51:11.669+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5.py", line 10
    !pip install snowflake-connector-python
    ^
SyntaxError: invalid syntax
[2025-03-05T05:51:11.670+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T05:51:11.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5.py took 0.022 seconds
[2025-03-05T05:51:42.259+0000] {processor.py:186} INFO - Started process (PID=299) to work on /opt/airflow/dags/data226_hwk5.py
[2025-03-05T05:51:42.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5.py for tasks to queue
[2025-03-05T05:51:42.261+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:51:42.261+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T05:51:42.269+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:51:42.268+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5.py", line 10
    !pip install snowflake-connector-python
    ^
SyntaxError: invalid syntax
[2025-03-05T05:51:42.269+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T05:51:42.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5.py took 0.026 seconds
[2025-03-05T05:52:12.877+0000] {processor.py:186} INFO - Started process (PID=310) to work on /opt/airflow/dags/data226_hwk5.py
[2025-03-05T05:52:12.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5.py for tasks to queue
[2025-03-05T05:52:12.879+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:52:12.878+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T05:52:12.885+0000] {logging_mixin.py:190} INFO - [2025-03-05T05:52:12.885+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5.py", line 10
    !pip install snowflake-connector-python
    ^
SyntaxError: invalid syntax
[2025-03-05T05:52:12.886+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T05:52:12.898+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5.py took 0.024 seconds
[2025-03-05T06:41:16.949+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:41:16.950+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5.py for tasks to queue
[2025-03-05T06:41:16.951+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:41:16.951+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:41:16.975+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:41:16.972+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5.py", line 116, in <module>
    load(lines, target_table)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 373, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 254, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3273, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3192, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
[2025-03-05T06:41:16.976+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:41:16.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5.py took 0.037 seconds
[2025-03-05T06:41:47.684+0000] {processor.py:186} INFO - Started process (PID=289) to work on /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:41:47.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5.py for tasks to queue
[2025-03-05T06:41:47.686+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:41:47.686+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:41:47.706+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:41:47.702+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5.py", line 116, in <module>
    load(lines, target_table)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 373, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 254, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3273, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3192, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
[2025-03-05T06:41:47.707+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:41:47.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5.py took 0.036 seconds
[2025-03-05T06:42:18.467+0000] {processor.py:186} INFO - Started process (PID=300) to work on /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:42:18.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5.py for tasks to queue
[2025-03-05T06:42:18.469+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:42:18.469+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:42:18.493+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:42:18.488+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5.py", line 116, in <module>
    load(lines, target_table)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 373, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 254, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3273, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3192, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
[2025-03-05T06:42:18.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:42:18.501+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5.py took 0.039 seconds
[2025-03-05T06:42:49.247+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:42:49.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5.py for tasks to queue
[2025-03-05T06:42:49.249+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:42:49.249+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:42:49.276+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:42:49.271+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5.py", line 116, in <module>
    load(lines, target_table)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 373, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 254, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3273, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3192, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
[2025-03-05T06:42:49.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:42:49.288+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5.py took 0.044 seconds
[2025-03-05T06:43:20.018+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:43:20.018+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5.py for tasks to queue
[2025-03-05T06:43:20.020+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:43:20.019+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:43:20.040+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:43:20.037+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5.py", line 116, in <module>
    load(lines, target_table)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 373, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 254, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3273, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3192, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
[2025-03-05T06:43:20.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:43:20.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5.py took 0.034 seconds
[2025-03-05T06:43:50.810+0000] {processor.py:186} INFO - Started process (PID=333) to work on /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:43:50.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5.py for tasks to queue
[2025-03-05T06:43:50.812+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:43:50.811+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:43:50.831+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:43:50.827+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5.py", line 116, in <module>
    load(lines, target_table)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 373, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 254, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3273, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3192, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
[2025-03-05T06:43:50.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:43:50.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5.py took 0.034 seconds
[2025-03-05T06:44:21.598+0000] {processor.py:186} INFO - Started process (PID=344) to work on /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:44:21.599+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5.py for tasks to queue
[2025-03-05T06:44:21.600+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:44:21.600+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:44:21.622+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:44:21.619+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5.py", line 116, in <module>
    load(lines, target_table)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 373, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 254, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3273, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3192, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
[2025-03-05T06:44:21.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:44:21.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5.py took 0.035 seconds
[2025-03-05T06:44:52.393+0000] {processor.py:186} INFO - Started process (PID=356) to work on /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:44:52.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5.py for tasks to queue
[2025-03-05T06:44:52.395+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:44:52.395+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:44:52.417+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:44:52.413+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5.py", line 116, in <module>
    load(lines, target_table)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 373, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 254, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3273, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3192, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
[2025-03-05T06:44:52.417+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:44:52.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5.py took 0.035 seconds
[2025-03-05T06:45:23.143+0000] {processor.py:186} INFO - Started process (PID=367) to work on /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:45:23.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data226_hwk5.py for tasks to queue
[2025-03-05T06:45:23.145+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:45:23.144+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:45:23.163+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:45:23.160+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/data226_hwk5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data226_hwk5.py", line 116, in <module>
    load(lines, target_table)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 373, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 254, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3273, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3192, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
[2025-03-05T06:45:23.164+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data226_hwk5.py
[2025-03-05T06:45:23.172+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data226_hwk5.py took 0.033 seconds
